export const ERROR_CODES = {
  // AUTH
  AUTH_MISSING_CREDENTIALS: 'AUTH_001',
  AUTH_INVALID_CREDENTIALS: 'AUTH_002',
  AUTH_TOKEN_MISSING: 'AUTH_003',
  AUTH_TOKEN_INVALID: 'AUTH_004',
  AUTH_INVALID_INPUT: "AUTH_005", 

  // USER
  USER_NOT_FOUND: 'USER_001',
  USER_ALREADY_EXISTS: 'USER_002',
  USER_FORBIDDEN: 'USER_003',

  //menu
  MENU_NOT_FOUND: "MENU_001",
  MENU_INVALID_INPUT: "MENU_002",

  
} as const;
